name: Physix
main: me.spywhere.Physix.Physix
version: 0.5.5
description: >
    Apply gravity to your MC server.
commands:
   physix:
       description: Main command
       usage: Command not available.